title: Paul O. Mugume
logo: /images/Profile.jpg
description: Set your heart ablaze, go beyond your limits.
show_downloads: true
theme: jekyll-theme-minimal
relative_links:
  enabled: true
  collections: true
include:
  - main.md

# Example to add custom links
nav:
  - title: "Home"
    url: /README.md
  - title: "Test page"
    url: /main.md
